-- Chat
ALTER TABLE "Config" ADD COLUMN "aiChatEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Config" ADD COLUMN "aiChatChannelId" TEXT;
ALTER TABLE "Config" ADD COLUMN "aiChatPerUserPerDay" INTEGER NOT NULL DEFAULT 20;
ALTER TABLE "Config" ADD COLUMN "aiChatModel" TEXT NOT NULL DEFAULT 'MiniMax-Text-01';

-- TTS
ALTER TABLE "Config" ADD COLUMN "aiTtsEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Config" ADD COLUMN "aiTtsChannelId" TEXT;
ALTER TABLE "Config" ADD COLUMN "aiTtsPerUserPerDay" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Config" ADD COLUMN "aiTtsModel" TEXT NOT NULL DEFAULT 'speech-02-hd';
ALTER TABLE "Config" ADD COLUMN "aiTtsVoiceId" TEXT NOT NULL DEFAULT 'German_PlayfulMan';

-- Music
ALTER TABLE "Config" ADD COLUMN "aiMusicEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Config" ADD COLUMN "aiMusicChannelId" TEXT;
ALTER TABLE "Config" ADD COLUMN "aiMusicPerUserPerDay" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "Config" ADD COLUMN "aiMusicModel" TEXT NOT NULL DEFAULT 'music-1.5';

-- Video
ALTER TABLE "Config" ADD COLUMN "aiVideoEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Config" ADD COLUMN "aiVideoChannelId" TEXT;
ALTER TABLE "Config" ADD COLUMN "aiVideoPerUserPerDay" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "Config" ADD COLUMN "aiVideoModel" TEXT NOT NULL DEFAULT 'T2V-01';
