-- AlterTable
ALTER TABLE "Config" ADD COLUMN "logChannels" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Config" ADD COLUMN "logServerRoles" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Config" ADD COLUMN "logServer" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Config" ADD COLUMN "logInvites" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Config" ADD COLUMN "logEmojis" BOOLEAN NOT NULL DEFAULT false;
